version: '3.9'  
  
services:  
  nodejs-app:  
    build: .  
    ports:  
      - '3978:3978'  
    # environment:  
    #   - NODE_ENV=production  
    # env_file:  
    #   - .env  
    volumes:
      - ./.env:/app/.env
    networks:  
      - dify-network  

networks:  
  dify-network:  
    driver: bridge  